Texter/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Texter.Models;

namespace Texter.Controllers
{
    public class ContactController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<User> _userManager;

        public ContactController(UserManager<User> userManager, ApplicationDbContext db)
        {
            _db = db;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View(_db.Contacts.ToList());
        }

        public IActionResult AddContact(string id)
        {
            ViewBag.user = _db.Users.FirstOrDefault(x => x.Id == id);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddContact(Contact newContact)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            newContact.User = currentUser;
            _db.Contacts.Add(newContact);
            _db.SaveChanges();
            return RedirectToAction("Index", new { id = userId });

        }
    }
}

Texter/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Texter.Models;
using Texter.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Texter.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public UserController(UserManager<User> userManager, SignInManager<User> signInManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _db = db;
        }

        public IActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SignUp(SignUpViewModel model)
        {
            var user = new User { UserName = model.Email };
            IdentityResult createResult = await _userManager.CreateAsync(user, model.Password);
            Microsoft.AspNetCore.Identity.SignInResult result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, isPersistent: true, lockoutOnFailure: false);

            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

		public IActionResult Login()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Login(LoginViewModel model)
		{
			Microsoft.AspNetCore.Identity.SignInResult result = await _signInManager
				.PasswordSignInAsync(model.Email, model.Password, isPersistent: true, lockoutOnFailure: false);
			
            // In above line we are using SignInManagers Asysnchronous PasswordInaAsync method to sign a user in with their credentials.
		
            if (result.Succeeded)
			{
				return RedirectToAction("Index", "Home");
			}
			else
			{
				return View();
			}
		}

		[HttpPost]
		public async Task<IActionResult> LogOff()
		{
			await _signInManager.SignOutAsync();
			return RedirectToAction("Index", "Home");
		}
    }
}

Texter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
    <title>@ViewBag.Title</title>
</head>
<body>
 <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <h2><li class="navbarbrand">@Html.ActionLink("Texter", "Index", "Home")</li></h2>
    </ul>
    <ul class="nav navbar-nav navbar-right">

        @if(User.Identity.IsAuthenticated)  
        {
            <li class="user-nav1">Hello @User.Identity.Name 
                @Html.ActionLink("","Index", "Home")</li>  
				
		    <li class="user-nav2">
                @Html.ActionLink("PhoneBook","Index", "Contact")
			</li>

			<li class="user-nav2">
                @Html.ActionLink("Messages", "Index", "Contact")
			</li>	
				
           <li>		
             @using (Html.BeginForm("LogOff", "User"))
            {
                <input type="submit" class="logoff" value="Log off"/>
            }
            </li>
        }
        else
        {
            <li>@Html.ActionLink("SignUp","SignUp","User")</li>
            <li>@Html.ActionLink("Log in","Login","User")</li>  
        }
    </ul>
  </div>
</nav>
    <div>
        @RenderBody()
    </div>
</body>